### PR TITLE
Fix #15 SSR issue (window undefined)

### LINKED ISSUE #15: ReferenceError: window is not defined
Hi,

Thanks for working on this. The source you've pushed to npm invokes `window` even though its not required and also not in the original source code. This prevents this library from being used in server-side rendered react projects like Next.js

You might want to build the source with Webpack instead of babel directly.

**Workaround**
Vendorize src/* into your local project. Use the library with a relative import.

### PR DESCRIPTION
**Pull request by Sylchauf**
This small modification indicates to webpack to avoid the use of window object.

This is useful to use this lib in SSR projects (like Next.JS)

### CODE REVIEW

**Comment by lamyfarai** [comment]
@Sylchauf Merged. Thank you :))

**Comment by kiranvj** [comment]
I am still getting the window issue Gatsby. 

image

Does this work only in NextJS?

**Comment by Sylchauf** [comment]
> I am still getting the window issue Gatsby.
> 
> image
> 
> Does this work only in NextJS?

Have you tested with master ? There is no new release on npmjs since this merge.

**Comment by kiranvj** [comment]
> > I am still getting the window issue Gatsby.
> > image
> > Does this work only in NextJS?
> 
> Have you tested with master ? There is no new release on npmjs since this merge.

That might be the issue, I need to check with master.

**Pull request merged**
